const $ = id => document.getElementById(id);
let token, sessionId, profile = '', entities = {}, state = {}, socket, media, context, collector, editing, pollBusy = false;
let view = 'conversation';
let speechContext, speechSource, speechAbort, speakingId;
function stopSpeech(){speechAbort?.abort();speechAbort=null;try{speechSource?.stop();}catch{}speechSource=null;if(speechContext){speechContext.close();speechContext=null;}speakingId=null;}
async function speakResponse(r){await stopCapture();stopSpeech();speechAbort=new AbortController();speakingId=r.id;speechContext=new AudioContext();await speechContext.resume();const response=await fetch('/api/sessions/'+sessionId+'/speak',{method:'POST',headers:{'X-Local-Token':token,'Content-Type':'application/json'},body:JSON.stringify({response_id:r.id}),signal:speechAbort.signal});if(!response.ok)throw new Error((await response.json()).detail);const bytes=await response.arrayBuffer();if(speakingId!==r.id)return;const audio=await speechContext.decodeAudioData(bytes);if(speakingId!==r.id)return;speechSource=speechContext.createBufferSource();speechSource.buffer=audio;speechSource.connect(speechContext.destination);speechSource.onended=stopSpeech;speechSource.start();}
const titles = {conversation:'Conversación',tasks:'Pendientes',courses:'Cursos y proyectos',memories:'Recuerdos',documents:'Material de consulta',profiles:'Perfiles y voz',diagnostic:'Diagnóstico'};
function notice(message) { $('notice').textContent = message; $('notice').hidden = !message; }
function node(tag, text, cls) { const e = document.createElement(tag); if (text !== undefined) e.textContent = text; if(cls) e.className=cls; return e; }
const markdown=window.markdownit({html:false,linkify:false,breaks:true});
function rich(text){
 const formulas=[];
 const protectedText=text.replace(/\$\$([\s\S]*?)\$\$|\$([^\n$]+?)\$|\\\[([\s\S]*?)\\\]|\\\(([^\n]+?)\\\)/g,(_,a,b,c,d)=>{
  const index=formulas.push({tex:a??b??c??d,display:a!==undefined||c!==undefined})-1;
  return 'VMATHPLACEHOLDER'+index+'END';
 });
 const e=node('div',undefined,'formatted-response');e.innerHTML=markdown.render(protectedText);
 const walker=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 for(const textNode of nodes){
  const matches=[...textNode.textContent.matchAll(/VMATHPLACEHOLDER(\d+)END/g)];if(!matches.length)continue;
  const fragment=document.createDocumentFragment();let cursor=0;
  for(const match of matches){fragment.append(document.createTextNode(textNode.textContent.slice(cursor,match.index)));const formula=formulas[Number(match[1])];const span=node('span');if(formula)window.katex.render(formula.tex,span,{displayMode:formula.display,throwOnError:false,maxExpand:1000,trust:false});fragment.append(span);cursor=match.index+match[0].length;}
  fragment.append(document.createTextNode(textNode.textContent.slice(cursor)));textNode.replaceWith(fragment);
 }
 return e;
}
function action(label, handler, cls='small') { const b=node('button',label,cls); b.type='button'; b.onclick=()=>Promise.resolve(handler()).catch(e=>{if(e.name!=='AbortError')notice(e.message);});return b; }
async function api(path, data, method) {
 const r=await fetch('/api/'+path,{method:method || (data ? 'POST':'GET'),headers:{'X-Local-Token':token,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});
 const result=await r.json();if(!r.ok)throw new Error(typeof result.detail==='string'?result.detail:'Revisa los campos introducidos.');return result;
}
async function newSession(){ const r=await api('sessions',{mode:$('mode').value,timezone:$('timezone').value,live_answers:$('live-answers').checked});sessionId=r.id;state={utterances:{},responses:[],proposals:{}};renderSession(); }
async function profiles(){const list=await api('profiles');const sel=$('profile');sel.replaceChildren(node('option','Invitado · sin memoria personal'));sel.firstChild.value='';$('profiles-list').replaceChildren();for(const p of list){const o=node('option',p.display_name);o.value=p.id;sel.append(o);const c=node('div',undefined,'card entity');c.append(node('h3',p.display_name),node('p',p.voiceprint?'Huella registrada':'Sin huella de voz'),action('Usar este perfil',()=>select(p.id)));$('profiles-list').append(c);}sel.value=profile;}
async function select(id){await pause();await api('profile/select',{profile_id:id||null,confirmed:true});profile=id;$('profile').value=id;await newSession();await loadData();notice(id?'Perfil confirmado para esta sesión local.':'Modo invitado: sin acceso a memoria personal.');}
async function loadData(){entities={};for(const kind of ['courses','tasks','memories','documents']) {entities[kind]=profile?await api('data/'+kind):[];renderEntities(kind);} }
function renderEntities(kind){const container=$(kind+'-list');container.replaceChildren();if(!entities[kind]?.length){container.append(node('p',profile?'Aún no hay elementos guardados.':'Selecciona tu perfil para ver y guardar elementos.','muted'));return;}
 for(const e of entities[kind]){const card=node('article',undefined,'card entity');card.append(node('span',kind==='tasks'?e.status:kind==='memories'?e.memory_kind||'recuerdo':kind==='documents'?'fuente autorizada':'contexto','tag'),node('h3',e.title||e.name||(e.content||'').slice(0,70)));
 if(e.content)card.append(node('p',e.content));if(kind==='tasks'){const course=entities.courses?.find(c=>c.id===e.course_id);card.append(node('p',(course?.name||'Sin curso')+' · '+(e.due_date||'Sin fecha')));}if(e.aliases?.length)card.append(node('p','Alias: '+e.aliases.join(', ')));
 if(e.source)card.append(node('small','Procedencia: '+e.source.text+' · '+new Date(e.source.at).toLocaleString('es-PE')));
 if(e.needs_review)card.append(node('p','La intervención de origen cambió. Revisa este elemento antes de usarlo.'));if(e.valid_until)card.append(node('p','Vigente hasta '+e.valid_until));const actions=node('div',undefined,'actions');actions.append(action('Editar',()=>openEditor(kind,e)),action('Borrar',async()=>{if(confirm('¿Borrar este elemento? Se eliminará de los datos locales y se limpiará el contexto de la sesión.')){await api('data/'+kind+'/'+e.id,null,'DELETE');await loadData();await poll();}},'small danger'));card.append(actions);container.append(card);}}
let renderKey='';
function renderSession(){const tagged=$('speaker-labels').checked;const key=JSON.stringify([state,tagged]);if(key===renderKey)return;renderKey=key;const trans=$('transcript');trans.replaceChildren();const utterances=Object.values(state.utterances||{});if(!utterances.length){const empty=node('div',undefined,'empty');empty.append(node('span','⌁'),node('h3','Empieza con una idea'),node('p','Puedes hablar o escribir. El historial de esta sesión es temporal.'));trans.append(empty);}
 if(!tagged&&utterances.length){trans.append(node('p',utterances.map(u=>u.text_literal).join(' '),'plain-transcript'));}
 const groups=[];
 for(const u of utterances){
  const labels=u.intents||['Afirmación'];const type=labels.join(' · ');const previous=groups.at(-1);
  const conversational=labels.every(label=>['Afirmación','Referencia a otra persona'].includes(label));
  if(previous&&conversational&&previous.type===type&&previous.speaker===u.speaker&&previous.text.length+u.text_literal.length<1100){previous.items.push(u);previous.text+=' '+u.text_literal;}
  else groups.push({type,speaker:u.speaker,text:u.text_literal,items:[u]});
 }
 for(const group of tagged?groups:[]){
  const pending=group.items.some(u=>u.status==='provisional');
  const card=node('article',undefined,'utterance '+(pending?'provisional':''));
  const meta=node('div',undefined,'utterance-meta');
  meta.append(node('span',group.type),node('span',pending?'Escuchando…':group.speaker==='Sin atribuir'?'Voz sin identificar':group.speaker));
  card.append(meta,node('p',group.text));
  if(group.items.some(u=>u.overlap))card.append(node('small','Posible solapamiento de voces'));
  const details=node('details',undefined,'transcript-edits');details.append(node('summary','Editar texto o hablante'));
  for(const u of group.items){if(u.status==='provisional')continue;const row=node('div',undefined,'fragment-edit');if(group.items.length>1)row.append(node('p',u.text_literal));row.append(action('Editar',()=>openTranscript(u)));details.append(row);}
  card.append(details);trans.append(card);
 }
 trans.scrollTop=trans.scrollHeight;
 const proposals=$('proposals');proposals.replaceChildren();const ps=Object.values(state.proposals||{});$('proposal-count').textContent=ps.length;
 if(!ps.length)proposals.append(node('p','Las tareas y recuerdos aparecerán aquí como propuestas.','muted'));
 for(const p of ps){const c=node('article',undefined,'proposal');c.append(node('span',p.kind==='tasks'?'Tarea propuesta':'Recuerdo seleccionado','tag'),node('h4',p.title||p.content));if(p.kind==='tasks'){c.append(node('p',(p.due_date||'Sin fecha')+' · '+(entities.courses?.find(x=>x.id===p.course_id)?.name||'Sin curso')));if(p.uncertain)c.append(node('p','Mención incierta: no equivale a un compromiso.'));}if(p.clarification)c.append(node('p',p.clarification));c.append(action('Revisar y confirmar',()=>openEditor(p.kind,p,true)));proposals.append(c);}
 const responses=$('responses');responses.replaceChildren();if(state.state==='INTERPRETING')responses.append(node('p','Preparando una respuesta local…','checking'));for(const r of [...(state.responses||[])].reverse().slice(0,4)){const c=node('article',undefined,'response');if(r.questions?.length){for(const question of r.questions)c.append(node('h4',question,'detected-question'));c.append(node('small','Pregunta detectada en el audio · explicación general'));}c.append(rich(r.text||'Preparando explicación…'));if(r.status==='generando')c.append(node('small','Respondiendo…','checking'));if(r.status==='cancelada')c.append(node('small','Respuesta detenida'));if(r.evidence?.length){c.append(node('small',r.verification));for(const source of r.evidence)c.append(node('blockquote',source.source+': '+source.excerpt));}c.append(action('Escuchar respuesta',()=>speakResponse(r)));responses.append(c);}
 if(!state.responses?.length&&state.state!=='INTERPRETING')responses.append(node('p','Las respuestas usan el contexto autorizado de tu perfil.','muted'));}
function field(name,label,value='',type='text',options){const l=node('label',label);let input;if(options){input=node('select');for(const [v,t] of options){const o=node('option',t);o.value=v;input.append(o);}}else if(type==='textarea')input=node('textarea');else {input=node('input');input.type=type;}input.name=name;input.value=value??'';l.append(input);return l;}
function openEditor(kind,e={},proposal=false){if(!profile){notice('Selecciona o crea tu perfil antes de guardar.');return;}editing={kind,e,proposal};$('editor-title').textContent=proposal?'Revisar y confirmar':e.id?'Editar':'Añadir';const f=$('editor-fields');f.replaceChildren();
 if(kind==='courses'||kind==='documents')f.append(field('name','Nombre',e.name));
 if(kind==='courses')f.append(field('aliases','Alias, separados por comas',(e.aliases||[]).join(', ')));
 if(kind==='tasks'){f.append(field('title','Título',e.title,'textarea'),field('course_id','Curso o proyecto',e.course_id,'text',[['','Sin asignar'],...(entities.courses||[]).map(c=>[c.id,c.name])]),field('due_date','Fecha de vencimiento (sin hora)',e.due_date,'date'),field('status','Estado',proposal?'confirmada':e.status,'text',['confirmada','en curso','completada','cancelada','pendiente de aclaración'].map(s=>[s,s])));if(e.clarification)f.append(node('p',e.clarification));if(e.uncertain)f.append(node('p','Esta mención era incierta. Confirma solo si existe un compromiso real.'));}
 if(kind==='memories'||kind==='documents')f.append(field('content','Contenido',e.content,'textarea'));
 if(kind==='memories')f.append(field('scope','Ámbito',e.scope||'personal','text',['personal','proyecto','curso'].map(x=>[x,x])),field('memory_kind','Tipo',e.memory_kind||'episodio','text',['episodio','preferencia','decisión','contexto'].map(x=>[x,x])),field('valid_until','Vigente hasta (opcional)',e.valid_until,'date'));
 $('editor').showModal();}
function openTranscript(u){editing={kind:'transcript',e:u};$('editor-title').textContent='Corregir intervención';$('editor-fields').replaceChildren(field('text','Texto literal',u.text_literal,'textarea'),field('speaker','Atribución confirmada por ti',u.speaker));$('editor').showModal();}
$('editor-form').onsubmit=async e=>{e.preventDefault();try{const values=Object.fromEntries(new FormData(e.target));const {kind,e:item,proposal}=editing;if(kind==='transcript'){await api('sessions/'+sessionId+'/text',{...values,utterance_id:item.id,revision:item.revision});}else{if(values.aliases!==undefined)values.aliases=values.aliases.split(',').map(s=>s.trim()).filter(Boolean);for(const k of ['due_date','valid_until','course_id'])if(values[k]==='')values[k]=null;if(proposal)Object.assign(values,{session_id:sessionId,source_id:item.id,source_revision:item.revision});await api('data/'+kind+(item.id&&!proposal?'/'+item.id:''),values,item.id&&!proposal?'PUT':'POST');await loadData();}$('editor').close();await poll();notice('Cambios guardados.');}catch(err){notice(err.message);}};
$('editor-close').onclick=$('editor-cancel').onclick=()=>$('editor').close();
async function stopCapture(){socket?.close();socket=null;collector?.disconnect();collector=null;media?.getTracks().forEach(t=>t.stop());media=null;if(context){await context.close();context=null;}$('audio-source').disabled=false;$('speaker-labels').disabled=false;$('personal-voice').disabled=false;$('global-mic').textContent='Micrófono apagado';$('listen').textContent='Iniciar escucha';$('mic-state').textContent='● Micrófono apagado';$('mic-state').classList.remove('live');}
async function pause(){stopSpeech();await stopCapture();if(sessionId)await api('sessions/'+sessionId+'/pause',{});}
async function captureInput(sharing){
 if(!sharing)return navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});
 if(!navigator.mediaDevices.getDisplayMedia)throw new Error('Este navegador no permite compartir audio de una pestaña. Abre el asistente y el video en Chrome.');
 const stream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'browser'},audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},selfBrowserSurface:'exclude',systemAudio:'exclude'});
 const surface=stream.getVideoTracks()[0]?.getSettings().displaySurface;
 if(!stream.getAudioTracks().length||(surface&&surface!=='browser')){stream.getTracks().forEach(t=>t.stop());throw new Error('Elige la pestaña del video y activa Compartir audio; no selecciones una ventana o toda la pantalla.');}
 stream.getVideoTracks().forEach(t=>{t.enabled=false;});
 return stream;
}
async function startCapture(){stopSpeech();const sharing=$('audio-source').value==='tab';const stream=await captureInput(sharing);media=stream;await api('sessions/'+sessionId+'/cancel',{});context=new AudioContext({sampleRate:16000});if(context.sampleRate!==16000){await stopCapture();throw new Error('Tu navegador no permite captura a 16 kHz. Prueba Chrome o Edge.');}await context.audioWorklet.addModule('/ui/pcm-worklet.js');const source=context.createMediaStreamSource(new MediaStream(stream.getAudioTracks()));collector=new AudioWorkletNode(context,'pcm-collector',{channelCount:1,channelCountMode:'explicit'});source.connect(collector);const silence=context.createGain();silence.gain.value=0;collector.connect(silence).connect(context.destination);
 const ws=new WebSocket(`ws://${location.host}/api/audio/${sessionId}?token=${encodeURIComponent(token)}&speakers=${$('speaker-labels').checked}&personal=${$('personal-voice').checked}`);socket=ws;ws.binaryType='arraybuffer';collector.port.onmessage=e=>{collector?.port.postMessage('ack');if(e.data.dropped){notice('El navegador perdió fragmentos por sobrecarga. La transcripción puede estar incompleta.');}if(ws.readyState===WebSocket.OPEN){if(ws.bufferedAmount>128000){notice('La conexión se atrasó. Escucha detenida.');pause();return;}ws.send(e.data.pcm);}};
 ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.component_state){notice('Motor de transcripción local listo.');return;}if(data.error){notice(data.error);pause();return;}state.utterances??={};state.utterances[data.id]=data;renderSession();};ws.onclose=()=>{if(socket===ws){stopCapture();notice('Escucha finalizada. El audio de esta sesión se descartó.');}};ws.onerror=()=>{notice('No se pudo conectar el motor de voz.');pause();};stream.getTracks().forEach(t=>t.addEventListener('ended',()=>{if(media===stream)pause();},{once:true}));$('audio-source').disabled=true;$('speaker-labels').disabled=true;$('personal-voice').disabled=true;$('global-mic').textContent=sharing?'● Audio del video activo':'● Micrófono encendido';$('listen').textContent='Pausar escucha';$('mic-state').textContent=sharing?'● Audio del video activo':'● Micrófono encendido';$('mic-state').classList.add('live');}
$('listen').onclick=async()=>{try{if(media)await pause();else await startCapture();}catch(e){await stopCapture();notice(e.message);}};
$('close-session').onclick=async()=>{try{await pause();await api('sessions/'+sessionId+'/close',{});await newSession();notice('Sesión cerrada: texto temporal y audio descartados.');}catch(e){notice(e.message);}};
$('stop-response').onclick=async()=>{stopSpeech();try{await api('sessions/'+sessionId+'/cancel',{});notice('Respuesta detenida.');}catch(e){notice(e.message);}};
$('ask-form').onsubmit=async e=>{e.preventDefault();stopSpeech();try{await api('sessions/'+sessionId+'/text',{text:$('question').value});$('question').value='';await poll();}catch(e){notice(e.message);}};
$('speaker-labels').onchange=()=>{if($('speaker-labels').checked)$('personal-voice').checked=false;renderSession();};$('personal-voice').onchange=()=>{if($('personal-voice').checked)$('speaker-labels').checked=false;renderSession();};
$('audio-source').onchange=()=>{$('audio-help').hidden=$('audio-source').value!=='tab';};
$('live-answers').onchange=()=>api('sessions/'+sessionId+'/live-answers',{enabled:$('live-answers').checked}).catch(e=>notice(e.message));
$('mode').onchange=()=>api('sessions/'+sessionId+'/mode',{mode:$('mode').value}).catch(e=>notice(e.message));$('timezone').onchange=async()=>{await pause();await newSession();};
$('profile').onchange=()=>select($('profile').value).catch(e=>notice(e.message));
$('new-profile').onclick=async()=>{const name=prompt('Nombre del perfil');if(name?.trim()){try{const p=await api('profiles',{display_name:name.trim()});await profiles();await select(p.id);}catch(e){notice(e.message);}}};
for(const b of document.querySelectorAll('.add'))b.onclick=()=>openEditor(b.dataset.kind);
for(const b of document.querySelectorAll('.nav'))b.onclick=async()=>{view=b.dataset.view;for(const v of document.querySelectorAll('.view'))v.hidden=v.id!==view;for(const n of document.querySelectorAll('.nav'))n.classList.toggle('active',n===b);$('view-title').textContent=titles[view];if(view==='profiles')await profiles();if(view==='diagnostic')await diagnostic();};
async function diagnostic(){const result=await api('status');$('components').replaceChildren();const labels={transcription:'Transcripción',conversation:'Conversación inteligente',memory:'Memoria',voiceprint:'Huella de voz',diarization:'Atribución automática',speech:'Respuesta hablada',telegram:'Telegram',verification:'Verificación'};for(const [k,v]of Object.entries(result.components)){const c=node('article',undefined,'card entity');c.append(node('span',v.state,'tag'),node('h3',labels[k]),node('p',v.engine));$('components').append(c);}}
$('telegram-form').onsubmit=async e=>{e.preventDefault();try{$('telegram-result').textContent=JSON.stringify(await api('telegram/search',{text:$('telegram-query').value}),null,2);}catch(err){notice(err.message);}};
$('revoke').onclick=async()=>{try{await api('voiceprint',null,'DELETE');await profiles();notice('Huella eliminada de los datos locales.');}catch(e){notice(e.message);}};
async function recordVoice(enroll=true){if(!profile||(enroll&&!$('consent').checked)){notice('Selecciona tu perfil y acepta el consentimiento antes de registrar tu voz.');return;}try{await pause();const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1},video:false});media=stream;context=new AudioContext({sampleRate:16000});await context.audioWorklet.addModule('/ui/pcm-worklet.js');collector=new AudioWorkletNode(context,'pcm-collector');context.createMediaStreamSource(stream).connect(collector);const silent=context.createGain();silent.gain.value=0;collector.connect(silent).connect(context.destination);const chunks=[];let count=0;$('global-mic').textContent='● Micrófono encendido · registro voluntario';$('enrollment-status').textContent='Habla normalmente durante ocho segundos. Solo tu voz.';collector.port.onmessage=async e=>{collector?.port.postMessage('ack');if(e.data.dropped){await stopCapture();chunks.forEach(c=>c.fill(0));notice('Registro detenido por sobrecarga. Prueba de nuevo.');return;}chunks.push(new Float32Array(e.data.pcm));count+=chunks.at(-1).length;if(count>=128000){collector.port.onmessage=null;await stopCapture();const samples=new Float32Array(count);let offset=0;for(const chunk of chunks){samples.set(chunk,offset);offset+=chunk.length;chunk.fill(0);}const r=await fetch(enroll?'/api/voiceprint/enroll':'/api/voiceprint/compare',{method:'POST',headers:{'X-Local-Token':token,'X-Voice-Consent':'true','Content-Type':'application/octet-stream'},body:samples.buffer});samples.fill(0);chunks.length=0;const result=await r.json();if(!r.ok){notice(result.detail);$('enrollment-status').textContent='Registro no completado.';}else{$('enrollment-status').textContent=enroll?'Huella cifrada registrada. Audio descartado. Comparación aún experimental.':'Similitud: '+result.similarity.toFixed(3)+'. Sin decisión automática. Confirma la identidad manualmente.';await profiles();}}};setTimeout(()=>{if(media===stream){stopCapture();chunks.forEach(c=>c.fill(0));notice('Registro detenido por tiempo máximo.');}},12000);}catch(e){await stopCapture();notice(e.message);}}
$('enroll').onclick=()=>recordVoice(true);$('compare-voice').onclick=()=>recordVoice(false);
async function poll(){if(pollBusy||!sessionId)return;pollBusy=true;try{state=await api('sessions/'+sessionId);if(speakingId&&!state.responses?.some(r=>r.id===speakingId))stopSpeech();renderSession();}catch(e){notice(e.message);}finally{pollBusy=false;}}
async function init(){try{const response=await fetch('/api/bootstrap');token=(await response.json()).token;await profiles();await newSession();await loadData();await diagnostic();setInterval(poll,1000);}catch(e){notice(e.message);}}
window.addEventListener('pagehide',()=>{stopSpeech();media?.getTracks().forEach(t=>t.stop());socket?.close();if(sessionId)fetch('/api/sessions/'+sessionId+'/close',{method:'POST',headers:{'X-Local-Token':token,'Content-Type':'application/json'},body:'{}',keepalive:true});});init();
